apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-monitor
  namespace: osg-services
spec:
  selector:
    matchLabels:
      k8s-app: factory-monitor
  template:
    metadata:
      labels:
        k8s-app: factory-monitor
    spec:
      tolerations:
      - key: "nautilus.io/stashcache"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: factory-monitor
        image: aaarora/factory-monitor:latest 
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: etc/condor-elasticsearch/config/rabbitmq_osg.json
          name: rabbitmq
          readOnly: true
          subPath: rabbitmq_osg.json
        - mountPath: etc/condor-elasticsearch/config/influxdb.json
          name: influxdb
          readOnly: true
          subPath: influxdb.json
        - mountPath: etc/condor-elasticsearch/config/config.json
          name: hostconfig
          readOnly: true
          subPath: config.json
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      volumes:
        - name: influxdb
          secret:
            secretName: factory-config
            items: 
            - key: influxdb.json
              path: influxdb.json
            defaultMode: 0600
        - name: rabbitmq
          secret:
            secretName: factory-config
            items:
            - key: rabbitmq_osg.json
              path: rabbitmq_osg.json
            defaultMode: 0600
        - name: hostconfig
          configMap:
            name: host-config
            items:
            - key: config.json
              path: config.json

