resources:
  - factory.yaml

secretGenerator:
- name: factory-config
  files:
    - private/rabbitmq_osg.json
    - private/influxdb.json

configMapGenerator:
- name: host-config
  files:
    - config.json

generatorOptions:
  disableNameSuffixHash: true

namespace: osg-services
commonLabels:
  app: factory-monitor
